version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    container_name: app
    restart: always
    build: .
    ports:
      - "4000:4000"

volumes:
  db:
